#!/usr/bin/env python

from connection.connection_manager import FTPConnectionManager
from utils.util import Utils
import sys
import os

# A class for parsing through inputted user commands
class CommandParser:

    # Initializes the command parser and splits the user input into different 
    # parameters
    def __init__(self):
        self.command = sys.argv[1]
        self.path = sys.argv[2]
        if (len(sys.argv) == 4):
            self.path2 = sys.argv[3]
        else:
            self.path2 = ""

    # Parses through the user's inputted parameters, such as username, password, 
    # host, port, remote path, and local path (only host and remote path are 
    # required)
    def parse_command(self):
        # Determine which arg is remote and which is local
        if self.path[:6] == "ftp://":
            remote = self.path
            local = self.path2
            rp = 1
        else:
            remote = self.path2
            local = self.path
            rp = 2

        # Get username and password
        if "@" in remote:
            username_password = remote.split("@")[0].split("ftp://")[1]
            if ":" in username_password:
                user = username_password.split(":")[0]
                pw = username_password.split(":")[1]
            else:
                user = username_password
                pw = None
            remote = remote.split(username_password + "@")[1]
        else:
            remote = remote.split("ftp://")[1]
            user = None
            pw = None

        # Get host and port
        if ":" in remote:
            host = remote.split(":")[0]
            port = int(remote.split(":")[1].split("/")[0])
        else:
            host = remote.split("/")[0]
            port = 21

        # Get remote path
        remote = "/" + remote.split("/", 1)[1]

        ("Command: " + str(self.command))
        Utils.print_logs("Username: " + str(user))
        Utils.print_logs("Password: " + str(pw))
        Utils.print_logs("Host: " + str(host))
        Utils.print_logs("Port: " + str(port))
        Utils.print_logs("Remote: " + str(remote))
        Utils.print_logs("Local: " + str(local))
        Utils.print_logs("Remote Path: " + str(rp))

        return self.command, user, pw, host, port, remote, local, rp

# Run the program based on the user's inputted command and 
# paths. Supports functionality for ls, mkdir, rm, rmdir, cp, 
# and mv. 
if __name__ == "__main__":

    try:
        parser = CommandParser()

        command, username, password, host, port, remote, local, rp = parser.parse_command()

        connection = FTPConnectionManager(username, password, host, port)

        if command == "ls":
            connection.list_directory(remote)

        elif command == "mkdir":
            connection.make_directory(remote)

        elif command == "rm":
            connection.remove_file(remote)

        elif command == "rmdir":
            connection.remove_directory(remote)

        elif command == "cp":
            if rp == 1:
                connection.save_remote_file_to_local(remote, local)
            else:
                connection.upload_file_to_remote(local, remote)

        elif command == "mv":
            if rp == 1:
                connection.save_remote_file_to_local(remote, local)
                connection = FTPConnectionManager(username, password, host, port)
                connection.remove_file(remote)
            else:
                connection.upload_file_to_remote(local, remote)
                os.system("rm " + local)
    except Exception as exception:
        print (exception)
